name: MRFG

on:
  schedule:
    - cron: '0 */5 * * *'  # Runs every 5 hours
  push:
    branches:
      - main  # Runs whenever you push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to latest stable version

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Updated to latest stable version
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: start
        run: npm start
